name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  typescript-build:
    name: Build - TypeScript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.11.0

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter @commercetools/ct-agent-toolkit run build

      - name: Clean
        run: pnpm --filter @commercetools/ct-agent-toolkit run clean

      - name: Lint
        run: pnpm --filter @commercetools/ct-agent-toolkit run lint

      - name: Prettier
        run: pnpm --filter @commercetools/ct-agent-toolkit run prettier-check

      - name: Test
        run: pnpm --filter @commercetools/ct-agent-toolkit run test

  modelcontextprotocol-build:
    name: Build - Model Context Protocol
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.11.0

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter @commercetools/mcp-essentials run build

      - name: Clean
        run: pnpm --filter @commercetools/mcp-essentials run clean

      - name: Lint
        run: pnpm --filter @commercetools/mcp-essentials run lint

      - name: Prettier
        run: pnpm --filter @commercetools/mcp-essentials run prettier-check

      - name: Test
        run: pnpm --filter @commercetools/mcp-essentials run test
